language: node_js
node_js:
  - 12.16.1 # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

# before_deploy:
#   - npm run build-client # make the bundle
#   - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy: # see README for details on these keys
  skip_cleanup: true
  provider: heroku
  app: ci-stannie
  api_key:
    secure: PgLZHV5nmqkIdTQbvm+QFJm1ytv52HwYWoVQJjKidPK708ZdnW3bb1TY0bC29uNTYzLZ7ilSPN0tXB91IIPgpTm6Xa8fS35fJPF++agabY2Pr4Y4PMkzfoCJGT0A4YMgGt/sQGGqnTjZesPFY1uNtcwj7hO8q6zB1YxDvvQ5/Qx/z8XlssFgvXtpRN3kkfmWrz3KUJDr+f3hSKuGzaGThCQctdN/Kflm3EEJsA8qDBNsnKPl6/INhjVBF0qSisc9uxenxRvzmOw2D3Yuj/wM+YPebLBgNSCaENhLII4OfRFzHh8AjxqXnwciKqqXZG3gWJCEqC08OyteQzIuyLBpWo9zUHKAWD1hfyrtn3wh6XJ8zoaXvtmQ5RI+brqOZacqRU+BlNrLp4HM4l7wfgUA9p1ng6aKsHKew5rDDTne0StIhnjyWZkU7Q/5dffHgAKFTW0Tc76SQkAfeXKi4I4S6c1yjCtKzxas5eSjpGy2RDUFoXQV4ijNM+oQV5CP1ppmF2mGAcSfOte9VSxtGrR6ehbWowLbpIYRfC8r7xIutrFr7UgsUUDCf4ooGqfnrzFoJzIVyaDCpxLzqBJqRGs6gzuPPzB9oDztnxh/Fw7E5C9pfjuA71pBk5/oRUS8cD1pPM+v6pfzQBCd9CJWqZG/xnP6Bpf7g+OABVYzfQJaj0k=
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
